spring.application.name=food-app

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/saveur_db
spring.datasource.username=root
spring.datasource.password=1234

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080

# Razorpay
razorpay.key.id=rzp_test_T4z8JPj8rOjVaa
razorpay.key.secret=i0LYjtvHHXyuOS3pMqG151UP

# Allow React frontend
spring.web.cors.allowed-origins=http://localhost:3000